Repository yiisoft/composer-config-plugin, pull requests merged in 2020-05, with the labels that each got.

#42 Add test for rebuild
  .travis.yml
  README.md
  phpunit.xml.dist
  src/Builder.php
  tests/Integration/Environment/composer.json
  tests/Integration/RebuildHook.php
Labels: status:code review, type:bug, type:test

#50 Make finding base dir compatible with how it was previously done
  src/Builder.php
Labels: type:bug

#54 Fixed fail with using a short closure
  composer.json
  tests/Integration/Environment/config/params.php
  tests/Integration/Tests/Config/ParamsConfigTest.php
Labels: status:code review

#53 Feature: not interpret env in compiled files
  src/Env.php
  src/Util/EnvEncoder.php
  src/Util/Helper.php
  tests/Integration/Environment/config/params.php
  tests/Integration/Tests/Config/ParamsConfigTest.php
  tests/Unit/Util/HelperTest.php
Labels: type:docs

#60 Fix tests on Windows
  .github/workflows/build.yml
  tests/Integration/ComposerUpdateHook.php
  tests/Integration/Environment/composer.json
Labels: status:code review

#64 Remove tests for deleted ReverseValues
  tests/Integration/Environment/config/params.php
  tests/Integration/Packages/first-vendor/first-package/config/params.php
  tests/Integration/Packages/first-vendor/second-package/config/params.php
  tests/Integration/Packages/second-vendor/first-package/config/params.php
  tests/Integration/Packages/second-vendor/second-package/config/params.php
  tests/Integration/Tests/Config/ParamsConfigTest.php
Labels: type:test
