Repository yiisoft/composer-config-plugin, pull requests merged in 2020-08, with the labels that each got.

#112 Minor change exception message in ReaderFactory
  src/Reader/ReaderFactory.php
Labels: status:code review

#114 Add test for alternatives with variable
  tests/Integration/Environment/config/alt/with-variable-params.php
  tests/Integration/Environment/config/alternatives.json
  tests/Integration/Tests/Config/AlternativesTest.php
Labels: type:test

#116 Remove variables, add `Builder::require('my-config')` that can be used for sub-configs
  CHANGELOG.md
  README.md
  src/Builder.php
  src/Reader/PhpReader.php
  src/Util/BuilderRequireEncoder.php
  src/Util/Helper.php
  tests/Integration/Environment/composer.json
  tests/Integration/Environment/config/required.php
  tests/Integration/Environment/config/web.php
  tests/Integration/Tests/Config/WebConfigTest.php
Labels: status:code review

#108 Add testcase for supporting wildcard. Closed #103
  README.md
  tests/Integration/Environment/composer.json
  tests/Integration/Environment/config/module1/params.php
  tests/Integration/Environment/config/module2/params.php
  tests/Integration/Environment/config/params-1.php
  tests/Integration/Environment/config/params-2.php
  tests/Integration/Tests/Config/ParamsConfigTest.php
Labels: status:code review

#83 Removed aliases.php
  CHANGELOG.md
  src/Builder.php
  src/Config/ConfigFactory.php
  src/Config/System.php
  src/Package/AliasesCollector.php
  src/Plugin.php
Labels: status:ready for merge
